package modelo;
// Generated 20-ene-2021 19:56:47 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

	private byte idDep;
	private String nombre;
	private String localidad;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Departamento() {
	}

	public Departamento(byte idDep, String nombre) {
		this.idDep = idDep;
		this.nombre = nombre;
	}

	public Departamento(byte idDep, String nombre, String localidad, Set<Empleado> empleados) {
		this.idDep = idDep;
		this.nombre = nombre;
		this.localidad = localidad;
		this.empleados = empleados;
	}

	public byte getIdDep() {
		return this.idDep;
	}

	public void setIdDep(byte idDep) {
		this.idDep = idDep;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
