package modelo;
// Generated 20-ene-2021 19:56:47 by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private short idEmp;
	private Departamento departamento;
	private String apellido;
	private String oficio;
	private Date fechaAlta;
	private float salario;
	private float comision;

	public Empleado() {
	}

	public Empleado(short idEmp, Departamento departamento, String apellido, String oficio, Date fechaAlta,
			float salario, float comision) {
		this.idEmp = idEmp;
		this.departamento = departamento;
		this.apellido = apellido;
		this.oficio = oficio;
		this.fechaAlta = fechaAlta;
		this.salario = salario;
		this.comision = comision;
	}

	public short getIdEmp() {
		return this.idEmp;
	}

	public void setIdEmp(short idEmp) {
		this.idEmp = idEmp;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public float getSalario() {
		return this.salario;
	}

	public void setSalario(float salario) {
		this.salario = salario;
	}

	public float getComision() {
		return this.comision;
	}

	public void setComision(float comision) {
		this.comision = comision;
	}

}
